insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('INDIGO','CCU','BLR',3560);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('VISTARA','DEL','MUM',8955);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('AIR INDIA','MAA','JAI',1857);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('KINGFISHER','BGP','NYC',4500);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('AIR ASIA','BBI','IMF',5000);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('ETIHAD','CHR','DXB',65000);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('EMIRATES','JSR','DTR',5000);
insert into Flight (FLIGHT_NAME, SOURCE, DESTINATION, PRICE) values('GO FIRST','PTN','BGP',2500);